class Fraction:
    #properties
    def __init__(self, s , m, ss , mm):
        self.soorat1 = s
        self.makhraj2 = m
        self.soorat2 = ss
        self.makhraj2 = mm
    #methods
    def sum(self) : 
        ...
    def sub(self):
        ...
    def mul(self) :
        ...
    def div(self):
        ...
    def Convert_fractions_to_percentages(self):
        ...
    def BMM(self):
        ...
    def KMM(self):
        ...